import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'linear-gradient': 'linear-gradient(var(--tw-gradient-stops))',
        'nht-card': "url('/nhtcard.png')",
        'lp-card': "url('/leadpadlerscards.png')",
        'rzfx-card': "url('/rockzfxcard.png')",
        'rzfx-bg1': "url('/csimages/rzfxbg1.png')",
        'rzfx-bg2': "url('/csimages/rzfxbg2.png')",
        'rzfx-bg3': "url('/csimages/rzfxbg3.png')",
        'rzfx-bg4': "url('/csimages/rzfxbg4.png')",
        'rzfx-bg5': "url('/csimages/rzfxbg5.png')",
        'rzfx-bg6': "url('/csimages/rzfxbg6.png')",
        'rzfx-bg7': "url('/csimages/rzfxbg7.png')",
        'rzfx-bg8': "url('/csimages/rzfxbg8.png')",
        'rzfx-bg9': "url('/csimages/rzfxbg9.png')",
        'rzfx-bg10': "url('/csimages/rzfxbg10.png')",
        'nht-bg1': "url('/nht/nhtbg1.png')",
        'nht-bg2': "url('/nht/nhtbg2.png')",
        'nht-bg3': "url('/nht/nhtbg3.png')",
        'nht-bg4': "url('/nht/nhtbg4.png')",
        'nht-bg5': "url('/nht/nhtbg5.png')",
        'nht-bg6': "url('/nht/nhtbg6.png')",
        'nht-bg7': "url('/nht/bgps.png')",
        'nht-bg8': "url('/nht/nhtabc.png')",
        nhtbg1: "url('/nhtbg.webp')",

        lp1: "url('/lp/bg1.png')",
        lp2: "url('/lp/bg2.png')",
        lp3: "url('/lp/bg3.png')",
        lp4: "url('/lp/bg4.png')",
        sfcard: "url('/scantifix/card.png')",
        sf1: "url('/scantifix/bg1.png')",
        sf2: "url('/scantifix/bg2.png')",
        sf3: "url('/scantifix/bg3.png')",
        sf4: "url('/scantifix/bg4.png')",
        sf5: "url('/scantifix/bg5.png')",
        sf6: "url('/scantifix/bg6.png')",
        sf7: "url('/scantifix/bg7.png')",
        sf8: "url('/scantifix/bg8.png')",
        na1: "url('/na/bg1.png')",
        pg1: "url('/pg/bg1.png')",
        pg2: "url('/pg/bg2.png')",
        pg3: "url('/pg/bg3.png')",
        ippc1: "url('/ippc/bg1.png')",
        ippc2: "url('/ippc/bg2.png')",
        ippc3: "url('/ippc/bg3.png')",
        ippc4: "url('/ippc/text.png')",
        ippc5: "url('/ippc/bg5.png')",
        ippc6: "url('/ippc/bg6.png')",
        ippc7: "url('/ippc/bg7.png')",
        ippc8: "url('/ippc/bg8.png')",
        ippc9: "url('/ippc/bg9.png')",
        apollo2: "url('/apollo/bg2.png')",
        apollo1: "url('/apollo/bg1.png')",
        pfbcard: "url('/pfb/Card.png')",
        pfb1: "url('/pfb/bg1.png')",
        pfb2: "url('/pfb/cake.png')",
        pfb3: "url('/pfb/bg3.png')",
        pfb4: "url('/pfb/bg4.png')",
        pfb5: "url('/pfb/bg5.png')",
        bc1: "url('/bc/bg1.png')",
        bc2: "url('/bc/bg2.png')",
        bc3: "url('/bc/bg3.png')",
        bengal1: "url('/bengal/bg1.png')",
        bengal2: "url('/bengal/bg2.png')",
        bengal3: "url('/bengal/bg3.png')",
        sccard: "url('/mobileapps/sc/card.png')",
        scbg1: "url('/mobileapps/sc/bg1.png')",
        scbg2: "url('/mobileapps/sc/bg2.png')",
        scbg3: "url('/mobileapps/sc/bg3.png')",
        scbg4: "url('/mobileapps/sc/bg4.png')",
        scbg5: "url('/mobileapps/sc/bg5.png')",
        ylbg1: "url('/mobileapps/yalaxi/bg1.png')",
        srbg1: "url('/mobileapps/sr/bg1.png')",
        srbg2: "url('/mobileapps/sr/bg2.png')",
        srbg3: "url('/mobileapps/sr/bg3.png')",
        srbg4: "url('/mobileapps/sr/bg4.png')",
        drbg1: "url('/mobileapps/doroos/bg1.png')",
        drbg2: "url('/mobileapps/doroos/bg2.png')",
        drbg3: "url('/mobileapps/doroos/bg3.png')",
        drbg4: "url('/mobileapps/doroos/bg4.png')",
        ndubg1: "url('/mobileapps/ndusapp/bg1.png')",
        ndubg2: "url('/mobileapps/ndusapp/bg2.png')",
        ndubg3: "url('/mobileapps/ndusapp/bg3.png')",
        ndubg4: "url('/mobileapps/ndusapp/bg4.png')",
        ndubg5: "url('/mobileapps/ndusapp/bg5.png')",
        ndubg6: "url('/mobileapps/ndusapp/box42.png')",
      },
      colors: {
        nht: '#006360',
        lp: '#792C21',
        na: '#4580AE',
        pg: '#00E0C5',
        pgc2: '#3E638F',
        ippc_pc: '#283E62',
        ippc_pc2: '#243A5F',
      },
      clipPath: {
        'custom-polygon':
          'polygon(83% 23%, 100% 47%, 85% 69%, 25% 69%, 0% 50%, 21% 23%)',
      },

      boxShadow: {
        'glow-white': '0 0 10px 5px rgba(255, 255, 255, 0.6)',
        'glow-yellow': '0 0 10px 5px rgba(238, 173, 4, 0.6)',
        'glow-blue': '0 0 10px 5px rgba(9, 24, 75, 0.6)',
        'glow-gray': '0 0 10px 5px rgba(190, 190, 190, 0.6)',
      },
    },
  },
  plugins: [],
};
export default config;
